<?php

declare(strict_types=1);

namespace CommissionTask\Components\Storage\Exceptions;

use CommissionTask\Components\Storage\Exceptions\Interfaces\CommissionTaskStorageException as CommissionTaskStorageExceptionContract;
use CommissionTask\Exceptions\CommissionTaskOutOfBoundsException;

final class CommissionTaskOutOfBoundsStorageException extends CommissionTaskOutOfBoundsException implements CommissionTaskStorageExceptionContract { }
