currencies:
  baseCurrency: 'EUR'
  rateScale: 6
  acceptable:
    - currencyCode: 'EUR'
      scale: 2
    - currencyCode: 'USD'
      scale: 2
    - currencyCode: 'JPY'
      scale: 0
currenciesApi:
  maxRequestsAttempts: 3
feeCalculator:
  roundedOffDigitsNumber: 1
  feeRateDeposit: '0.0003'
  feeRateWithdrawPrivate: '0.003'
  feeRateWithdrawBusiness: '0.005'
  nontaxableAmountWithdrawPrivate: '1000.00'
  nontaxableCurrencyCodeWithdrawPrivate: 'EUR'
  preferentialOperationsNumberWithdrawPrivate: 3
